Новые фильтры
YourCodeReview/jobs pull request #11
Opened 2024-04-22 18:04 UTC by Devayter

2024-04-22 18:06 UTC, Devayter commented
Попытка ПР

2024-04-22 19:30 UTC, saigono commented on backend/crud.py
> +        location: list[str]
```suggestion
        locations: list[str]
```

2024-04-22 19:32 UTC, saigono commented on backend/api/routes.py
> +            location or [],
Непонятно, зачем дублируются значения по умолчанию

2024-04-22 19:32 UTC, saigono commented on .DS_Store
этот файл не нужен

2024-04-22 19:35 UTC, saigono commented on backend/crud.py
> +def get_vacancies(db: Session, skip, limit: int):
Нет смысла в этом изменении

2024-04-22 19:36 UTC, saigono commented on backend/crud.py
> +def get_vacancies_with_specialities(
Сейчас есть три функции выполняющие одно и то же:

get_vacancies
get_vacancies_by_filters
get_vacancies_with_specialities

оставьте только get_vacancies_by_filters, только под названием get_vacancies

2024-04-22 19:37 UTC, saigono requested changes
См. комментарии

2024-04-23 13:23 UTC, Devayter commented on backend/crud.py
> +        location: list[str]
Везде изменил на множественное число, нужно обновить миграции

2024-04-24 15:52 UTC, merged