frontend jobs filter
YourCodeReview/jobs pull request #17
Opened 2024-04-30 06:17 UTC by AntonKulagin

Добавляет часть функциональности для фильтрации.

2024-04-30 11:48 UTC, AntonKulagin commented
![Снимок экрана (228)](https://github.com/YourCodeReview/jobs/assets/89462331/c0162dde-6507-4c34-9561-fa2c6e75fa6a)

2024-04-30 17:51 UTC, AntonKulagin commented
![Снимок экрана (229)](https://github.com/YourCodeReview/jobs/assets/89462331/578d936c-79e7-4e7a-9ddf-d1150f7f96bc)

2024-05-05 08:22 UTC, AntonKulagin commented
![Снимок экрана (231)](https://github.com/YourCodeReview/jobs/assets/89462331/726a3e0b-c05f-433f-9afb-85305191c01f)

2024-05-09 19:03 UTC, AntonKulagin commented
![Снимок экрана (234)](https://github.com/YourCodeReview/jobs/assets/89462331/c4c08f70-8ef7-444e-a837-2c02dbf46f54)

2024-05-10 09:55 UTC, AntonKulagin commented
![Снимок экрана (235)](https://github.com/YourCodeReview/jobs/assets/89462331/602a2214-ec6b-4f24-b4db-e131a6a45ae5)

2024-05-10 12:33 UTC, AntonKulagin commented
![Снимок экрана (237)](https://github.com/YourCodeReview/jobs/assets/89462331/e3292d67-5c14-4a5b-b47b-2fec8c69475b)

2024-05-10 14:38 UTC, saigono requested changes
Очень мелкие исправления и потом можно мержить

2024-05-10 14:38 UTC, saigono commented on backend/requirements.txt
> +greenlet==3.0.3
не думаю что эти изменения релевантны для ПР

2024-05-10 14:38 UTC, saigono commented on frontend/src/components/Jobs/VueLocationsTools.vue
> +    placeholder="Выберете город"
Выберите

2024-05-10 14:55 UTC, AntonKulagin commented on backend/requirements.txt
> +greenlet==3.0.3
А что в этом случае делать? Поменять цифры обратно?

2024-05-10 15:27 UTC, saigono approved these changes

2024-05-10 16:24 UTC, merged