Dev/link parser
YourCodeReview/jobs pull request #19
Opened 2024-05-09 16:22 UTC by Valpydeveloper

1) Add bs4 linkedin parser

2024-05-10 06:01 UTC, saigono requested changes
Два главных комментария:
- убрать скрапи
- возвращать значение из функции "parse_all_page" вместо того чтобы писать в json файл

2024-05-10 06:01 UTC, saigono commented on backend/parsing/link_vac_bs4.py
> +parse_all_page(0)
вызов не нужен (пока что)

2024-05-10 06:01 UTC, saigono commented on backend/parsing/link_vac_bs4.py
> +def parse_all_page(start):
Не очень понятно зачем нужно передавать этот параметр в функцию

2024-05-11 17:31 UTC, Valpydeveloper commented on backend/parsing/link_vac_bs4.py
> +start = -25
Переменная была в изначальном варианте, когда не знал как задать цикл ) убрал

2024-05-11 17:32 UTC, Valpydeveloper commented on backend/parsing/link_vac_bs4.py
> +    print(detail_url)
print(detail_url) был нужен для отладки, тоже убрал. Строки 63,64,65 нужны для получения ссылки на страницу с описанием вакансии

2024-05-11 17:39 UTC, Valpydeveloper commented on backend/parsing/link_vac_bs4.py
> +    url_vacancy = vacancy.find("a", class_="base-card__full-link absolute top-0 right-0 bottom-0 left-0 p-0 z-[2]").get("href")
Сделал все кавычки в файле одинарными

2024-05-11 17:42 UTC, Valpydeveloper commented on backend/parsing/link_vac_bs4.py
> +from bs4 import BeautifulSoup
Отсортировал через isort

2024-05-11 17:49 UTC, Valpydeveloper commented on backend/parsing/link_vac_bs4.py
> +        start += 25
Единственный комментарий, который пока не понял ) можно поподробнее описать суть проблемы ? Одна страница линки по тому урлу на который делается первый запрос, возвращает 25 объектов класса "base-card relative w-full hover:no-underline focus:no-underline base-card--link base-search-card base-search-card--link job-search-card", для каждого из них выполняется функция которая парсит эту самую одну страницу

2024-05-11 17:56 UTC, Valpydeveloper commented on backend/parsing/link_vac_bs4.py
> +parse_all_page(0)
убрал

2024-05-11 18:02 UTC, Valpydeveloper commented on backend/parsing/link_vac_bs4.py
> +    while start < 1000:
Ну да, разница только в них, суть двух циклов в том, чтобы после первого цикла значение старт обнулялось. Попробую придумать как укоротить, можно сделать надцикл for, который будет идти по списку geoid и для каждого из них вызывать цикл for. Я правильно понял замечание ?

2024-05-11 18:03 UTC, Valpydeveloper commented on backend/parsing/link_vac_bs4.py
> +def parse_all_page(start):
тоже убрал )

2024-05-12 07:31 UTC, saigono commented on backend/parsing/link_vac_bs4.py
> +        start += 25
Непонятно что за магическое число 25, лучше написать небольшой комментарий

2024-05-12 07:31 UTC, saigono commented on backend/parsing/link_vac_bs4.py
> +    while start < 1000:
Да, правильно

2024-05-12 07:31 UTC, saigono commented on backend/parsing/link_vac_bs4.py
> +        json.dump(vacancy, json_file, indent=4, ensure_ascii=False)
Всё ещё нужно поменять :)

2024-05-12 13:38 UTC, Valpydeveloper commented on backend/parsing/link_vac_bs4.py
> +        url = "https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?keywords=&location=&geoId=101705918&trk=public_jobs_jobs-search-bar_search-submit&start=" + str(start)
Переделал в f строку

2024-05-12 13:41 UTC, Valpydeveloper commented on backend/parsing/link_vac_bs4.py
> +        start += 25
Тут я ошибся, изменил значение с 25 на 10. В самом коде добавил документацию, где упомянул для чего это значение

2024-05-12 13:42 UTC, Valpydeveloper commented on backend/parsing/link_vac_bs4.py
> +    while start < 1000:
Сделано

2024-05-14 10:08 UTC, saigono commented on backend/parsing/link_vac_bs4.py
> +        json.dump(vacancy, json_file, indent=4, ensure_ascii=False)
Жду…

2024-05-15 10:18 UTC, saigono approved these changes

2024-05-15 10:19 UTC, merged